### ISSUE TITLE
wait-fuse.sh failed in etcd

### ISSUE THREAD

**Issue by yeya24** [pingcap/chaos-mesh#223]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I tried to do iochaos to etcd container with the given [etcd-configmap](https://github.com/pingcap/chaos-mesh/blob/master/examples/chaosfs-configmap/etcd-configmap.yaml). But it shows
```
➜  chaosfs-configmap git:(io-examples) ✗ kubectl logs -f etcd-7b9b5486bd-nstj8 -c etcd
/tmp/scripts/wait-fuse.sh: 3: set: Illegal option -o pipefail
```

Seems `/bin/sh` doesn't support `-o pipefail`, ref: https://ideas.circleci.com/ideas/CCI-I-858.

Considering that so many images don't have `bash`, maybe it is better to update the script to make it work for most cases.

**Comment by yeya24** [comment]
For reproducing:
etcd-deployment.yml
``` yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: etcd
  namespace: test
  labels:
    app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          imagePullPolicy: IfNotPresent
          image: k8s.gcr.io/etcd:3.4.3-0
          args:
            - /usr/local/bin/etcd
            - -name=etcd
            - -advertise-client-urls=http://0.0.0.0:2379
            - -initial-advertise-peer-urls=http://0.0.0.0:2380
            - -listen-client-urls=http://0.0.0.0:2379
            - -listen-peer-urls=http://0.0.0.0:2380
            - -initial-cluster=etcd=http://0.0.0.0:2380
            - --data-dir=/var/run/etcd/default.etcd
            - -initial-cluster-state=new
            - -initial-cluster-token=etcd-cluster
          volumeMounts:
          - mountPath: /var/run/etcd
            name: datadir
      volumes:
        - emptyDir: {}
          name: datadir
```

etcd-configmap

``` yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaosfs-etcd
  namespace: default
  labels:
    app.kubernetes.io/component: webhook
data:
  chaosfs-etcd.yaml: |
    name: chaosfs-etcd
    initContainers:
    - name: inject-scripts
      image: pingcap/chaos-scripts:latest
      imagePullpolicy: Always
      command: ["sh", "-c", "/scripts/init.sh -d /var/run/etcd/default.etcd -f /var/run/etcd/fuse-data"]
    containers:
    - name: chaosfs
      image: pingcap/chaos-fs:latest
      imagePullpolicy: Always
      ports:
      - containerPort: 65534
      securityContext:
        privileged: true
      command:
        - /usr/local/bin/chaosfs
        - -addr=:65534
        - -pidfile=/tmp/fuse/pid
        - -original=/var/run/etcd/fuse-data
        - -mountpoint=/var/run/etcd/default.etcd
      volumeMounts:
        - name: datadir
          mountPath: /var/run/etcd
          mountPropagation: Bidirectional
    volumeMounts:
    - name: datadir
      mountPath: /var/run/etcd
      mountPropagation: HostToContainer
    - name: scripts
      mountPath: /tmp/scripts
    - name: fuse
      mountPath: /tmp/fuse
    volumes:
    - name: scripts
      emptyDir: {}
    - name: fuse
      emptyDir: {}
    postStart:
      etcd:
        command:
          - /tmp/scripts/wait-fuse.sh
```

annotate namespace
``` 
kubectl annotate --overwrite ns test admission-webhook.pingcap.com/init-request=chaosfs-etcd
```
