### ISSUE TITLE
Choose which pods can be tested for chaos 

### ISSUE THREAD

**Issue by AndyXia23** [pingcap/chaos-mesh#341]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Sometimes, I want to run pod chaos within specified pods, therefore, the expected feature is that users can choose which pods can be tested for chaos.

**Describe alternatives you've considered:**

Add a label for those pods that are expected to be used for chaos test.

**Comment by zhouqiang-cl** [comment]
@cwen0 PTAL

**Comment by YangKeao** [comment]
Doesn't `labelSelector` satisfies your requirement?

```
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-example
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  scheduler:
    cron: "@every 1m"
```

As this example, it will only kill pod whose label `app.kubernetes.io/component` is set to `tikv`.

If you need more complicate selectors, we plan to support [`matchExpressions`](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements) to support set-based requirements. Will this meet your needs?
