### ISSUE TITLE
Use templates to simplify the complexity of configuring sidecar ConfigMap

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#406]
## Feature Request

**Is your feature request related to a problem? Please describe:**
 

When we want to inject IOChaos, we need to define a ConfigMap for your application before starting chaos experiment and the ConfigMap have many fields that need to be full. And we found that most of the field values in different configmaps do not need to be changed

**Describe the feature you'd like:**

We can use a template to help define ConfigMap and the users just to set the PV path and the data directory of the application.  

For example, we can define a template named `chaosfs-configmap` and we can use it to define a sidecar ConfigMap for tikv: 

```
xxxx
template: chaosfs 
arguments: 
  dataPath: /var/lib/tikv/data
  pvName: tikv
  pvPath: xxx
```
