### ISSUE TITLE
How to visualize chaos output?

### ISSUE THREAD

**Issue by HillebrandtOldenberg** [pingcap/chaos-mesh#407]
## Question

How can I see the test results elegantly without running the recommended [benchmark](https://pingcap.com/docs/stable/benchmark/how-to-run-sysbench/)? Something like [web-show](https://github.com/pingcap/chaos-mesh/tree/master/examples/web-show) but for every type of chaos and with data output like [this](https://github.com/mrahbar/k8s-testsuite#test-results). I don't have enough resources to run the recommended benchmark.

Issues [148](https://github.com/pingcap/chaos-mesh/issues/148), [174](https://github.com/pingcap/chaos-mesh/issues/174), and [240](https://github.com/pingcap/chaos-mesh/issues/240) seem similar to what I'm trying to get at but I am confused as to their resolutions.

And if there is no elegant visualization method, where are the test logs located?

**Comment by cwen0** [comment]
@HillebrandtOldenberg I am sorry for your confusion. At present, we just can get the chaos output from the status field of chaos experiment for general applications, for example, assume that you have a chaos experiment named to `pod-fail-chaos` in `app-ns` namespace,  you can use the following command to get the status of this experiment: 

```
kubectl get podchaos pod-fail-chaos  -n app-ns -o yaml
``` 

After executing the above command, you can get the output: 

```
xxxx
  experiment:
    endTime: "2020-03-25T09:14:07Z"
    phase: Finished
    podChaos:
    - action: pod-failure
      hostIP: 172.16.4.86
      message: pause pod duration 30s
      name: tiflash-0
      namespace: app-ns 
      podIP: 10.233.122.175
    startTime: "2020-03-25T09:13:37Z"
``` 

The status field will show us the latest experiment result. 

In addition, we are adding a general chaos-dashboard and provide a easy-to-use chaos event interface for the application monitoring system to obtain chaos experimental information，eg: grafana plugin
