### ISSUE TITLE
PodChaos in version "v1alpha1" cannot be handled as a CustomResourceDefinition

### ISSUE THREAD

**Issue by HillebrandtOldenberg** [pingcap/chaos-mesh#430]
## Bug Report

**What version of Kubernetes are you using?**

Client & server: v1.18.0

**What did you do?**

Installed chaos-mesh by following the [manual ](https://github.com/pingcap/chaos-mesh/wiki/Deploy-Chaos-Mesh) until step 3. Next, used fabric8's [kubernetes-client](https://github.com/fabric8io/kubernetes-client) to launch the pod-failure action.

_Java code_
```
// Launching 10 echo servers to apply chaos to
List<HasMetadata> echoServer = kubernetesClient
    .load(new FileInputStream(myChaosMeshTestsPath + "echo-server-deployment.yaml")).get();
kubernetesClient.resourceList(echoServer).inNamespace(namespaceName).deletingExisting().createOrReplace();

// Waiting for all 10 pods to become available
kubernetesClient.apps().deployments().inNamespace(namespaceName).withName("echo-server")
    .waitUntilCondition(deployment -> Optional.ofNullable(deployment.getStatus())
        .map(DeploymentStatus::getAvailableReplicas)
        .orElse(-1).equals(10), 2, TimeUnit.MINUTES);

// Launching pod-failure action
CustomResourceDefinition aCustomResourceDefinition = kubernetesClient.customResourceDefinitions()
    .load(new FileInputStream(myChaosMeshTestsPath + "pod-failure.yaml")).get();
kubernetesClient.customResourceDefinitions().create(aCustomResourceDefinition);
```

_echo-server-deployment.yaml_
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 10
  selector:
    matchLabels:
      app: rcnit-chaos
  template:
    metadata:
      labels:
        app: rcnit-chaos
    spec:
      containers:
        - image: k8s.gcr.io/echoserver:1.4
          imagePullPolicy: IfNotPresent
          name: echo-server
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: rcnit-chaos
```

_pod-failure.yaml_
```
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
spec:
  action: pod-failure
  mode: one
  duration: "60s"
  selector:
    labelSelectors:
      app: rcnit-chaos
  scheduler:
    cron: "@daily"
```

**What did you expect to see?**
No error.

**What did you see instead?**
Error appearing at line `kubernetesClient.customResourceDefinitions().create(aCustomResourceDefinition)`:

`io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.99.184:8443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions. Message: PodChaos in version "v1alpha1" cannot be handled as a CustomResourceDefinition: no kind "PodChaos" is registered for version "pingcap.com/v1alpha1" in scheme "k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:54".`

**Addendum**
If I do the exact same steps manually using `kubectl`, there is no problem.
