### ISSUE TITLE
Experiment should be resumed immediately after not pausing

### ISSUE THREAD

**Issue by yeya24** [pingcap/chaos-mesh#450]
## Bug Report

**What version of Kubernetes are you using?**

**What did you do?**

Create a chaos with the config below. We have cron 10m and duration 9m.

``` yaml
apiVersion: pingcap.com/v1alpha1
kind: IoChaos
metadata:
  name: io-delay-example
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  configName: "chaosfs-test"
  path: ""
  selector:
    labelSelectors:
      app: test
  layer: "fs"
  delay: "1s"
  duration: "9m"
  scheduler:
    cron: "@every 10m"
```

After 10s the chaos started, I paused this chaos. Then 10s later, I set paused to false. I expected the chaos continue running. However, this chaos is still paused until its nextStart, which is 10m later. 

After the chaos resumes, we need to still inject the chaos in the current round, instead of waiting until the next round
