### ISSUE TITLE
Rename status field

### ISSUE THREAD

**Issue by yeya24** [pingcap/chaos-mesh#521]
Run the command `kubectl get timechaos -o yaml`, I found that the status field name is `podChaos`. This is not appropriate here. Maybe it is better to be `podRecord` to be consistent with the new chaos server API.

```
  status:
    experiment:
      endTime: "2020-05-18T18:42:18Z"
      phase: Running
      podChaos:
      - action: ""
        hostIP: 172.17.0.2
        message: time is shifted with -1h
        name: etcd-69bc969869-hjqbm
        namespace: chaos-testing
        podIP: 10.244.1.9
```
