### ISSUE TITLE
Kernel chaos nil pointer panic

### ISSUE THREAD

**Issue by yeya24** [pingcap/chaos-mesh#535]
## Bug Report

Version

```
master
```

Error log in Chaos Mesh controller

```
2020-05-21T19:21:06.192Z	ERROR	controllers.KernelChaos	Get container pid error	{"reconciler": "kernelchaos", "namespace": "chaos-testing", "name": "etcd-577c6ffdd4-wm6xg", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.16.4.67:31767: connect: no route to host\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/pingcap/chaos-mesh/controllers/kernelchaos.(*Reconciler).applyPod
	/src/controllers/kernelchaos/types.go:291
github.com/pingcap/chaos-mesh/controllers/kernelchaos.(*Reconciler).applyAllPods.func1
	/src/controllers/kernelchaos/types.go:259
golang.org/x/sync/errgroup.(*Group).Go.func1
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
2020-05-21T19:21:06.192Z	INFO	util	Creating client to chaos-daemon	{"node": "172.16.4.67"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13a0b3b]

goroutine 444 [running]:
github.com/pingcap/chaos-mesh/controllers/kernelchaos.(*Reconciler).applyPod(0xc0008f0330, 0x1967640, 0xc000169800, 0xc000a71000, 0xc000193400, 0x0, 0x0)
	/src/controllers/kernelchaos/types.go:313 +0x71b
github.com/pingcap/chaos-mesh/controllers/kernelchaos.(*Reconciler).applyAllPods.func1(0xc000534768, 0x0)
	/src/controllers/kernelchaos/types.go:259 +0x4e
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000796750, 0xc000796840)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

Reproduce steps:

1. create chaos mesh

```
helm3 install chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set bpfki.create=true
```

2. create etcd example

```
kubectl apply -f examples/etcd/etcd.yaml
```

3. create kernel chaos

```
apiVersion: pingcap.com/v1alpha1
kind: KernelChaos
metadata:
  name: kernel-chaos-1
  namespace: chaos-testing
spec:
  duration: 30s
  failKernRequest:
    callchain:
    - funcname: __x64_sys_mount
    failtype: 0
  mode: one
  scheduler:
    cron: '@every 60s'
  selector:
    labelSelectors:
      app: etcd
    namespaces:
    - chaos-testing
  value: ""
```
