### ISSUE TITLE
NetworkChaos Experiment Inject Latency Between Pod and External Endpoint

### ISSUE THREAD

**Issue by DannyeB** [pingcap/chaos-mesh#676]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I would like to be able to inject latency between a pod in the cluster and an external endpoint. This might be an externally hosted database or Redis instance etc

**Describe the feature you'd like:**
In the NetworkChaos experiment, I should be able to use an external URL as the target. Any traffic coming from my selected pods going to the external URL should get latency applied. This is what I was thinking it would look like:

```yaml
apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: block-external-sample
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app: microserviceb
    namespaces:
      - default
  direction: to
  target:
    selector:
      external: "https://mydburl.com"
  delay:
    latency: "300ms"
    correlation: "80"
    jitter: "90ms"

```

**Describe alternatives you've considered:**
I have thought about setting up a proxy pod inside my cluster and applying the latency to that. However, then I need to change my connection strings and that is not a very practical solution for me.

**Teachability, Documentation, Adoption, Migration Strategy:**
A lot of cloud services I work with, in Kubernetes use externally hosted solutions for the stateful parts such as databases. We need to cover the failure scenarios when these go down or the connections become slow.
