### ISSUE TITLE
externalTargets not working as expected with hostnames resolving to multiple ip addresses

### ISSUE THREAD

**Issue by vburckhardt** [pingcap/chaos-mesh#692]
## Bug Report

**What version of Kubernetes are you using?**
1.16

**What did you do?**

network chaos:
```
spec:
  action: delay
  delay:
    correlation: "0"
    jitter: 0ms
    latency: 10000ms
  direction: to
  duration: 59s
  externalTargets:
  - www.google.com
  mode: all
  scheduler:
    cron: '@every 1m'
  selector:
    labelSelectors:
      app: microserviceb
    namespaces:
    - default
  value: ""
```

**What did you expect to see?**

kube exec inside the pod, and run ping www.google.com
expecting to see ping delayed consistently for 59s, not delayed for 1s, and so on

**What did you see instead?**

ping delayed only from time to time, inconsistently.
